Use SD sw_pll for digital Rx on XS3 targets
xmos/lib_xua pull request #360
Opened 2024-01-09 14:41 UTC by ed-xmos

https://xmosjira.atlassian.net/jira/software/c/projects/UA/boards/54?assignee=557058%3A17873fbc-49d6-4971-8efb-a0de95f426a1&selectedIssue=UA-158

2024-01-10 14:22 UTC, xross commented on CHANGELOG.rst
> +  * CHANGED:   xcore-ai targets use sigma-delta software PLL for clock recovery of
xcore.ai

2024-01-10 14:24 UTC, xross commented on lib_xua/doc/rst/arch.rst
> +     from digital input. On xCORE-AI Clockgen may also work in
xcore.ai

2024-01-10 14:24 UTC, xross commented on lib_xua/doc/rst/feat_spdif_rx.rst
> +streams the codebase assumes the use of an external Cirrus Logic CS2100 device or lib_sw_pll on xCORE-AI designs.
xcore.ai

2024-01-10 14:25 UTC, xross commented on lib_xua/doc/rst/hw.rst
> +Either the locally generated clock (from the PL611) or the recovered low jitter clock (from the CS2100) may be selected to clock the audio stages; the xCORE-AI, the ADC/DAC and Digital output stages.
xcore.ai

2024-01-10 14:26 UTC, xross commented on lib_xua/doc/rst/sw_clocking.rst
> +Logic CS2100 device or use of lib_sw_pll (xCORE-AI only) for this purpose. Other devices may be
xcore.ai

2024-01-10 14:33 UTC, xross requested changes
Looks good to me, just small doc updates I highlighted. 

The wrapper, im not sure exactly why this doesn't live in lib_sw_pll but it's not a biggy for the moment. 

Looks like a fantastic addition to the codebase.

2024-01-10 16:40 UTC, ed-xmos commented
> Looks good to me, just small doc updates I highlighted.
> 
> The wrapper, im not sure exactly why this doesn't live in lib_sw_pll but it's not a biggy for the moment.
> 
> Looks like a fantastic addition to the codebase.

Yes I was wondering about the phase frequency detector logic living in sw_pll. It's subtly different from the stock one and also the SD is wrapped up in a loop with a select and other resource stuff and wanted to keep sw_pll generic. There's an SD example in sw_pll (using C rather than XC) but it differs in that the PI controller runs in client rather than the server as in usb_audio. In UA we need to keep the blocking time in clock gen very low due to 192kHz cases.. By keeping the lib generic you are not enforcing usage. I can see arguments both ways really.

2024-01-10 16:45 UTC, xross submitted a review, later dismissed

2024-01-12 16:40 UTC, xross commented on lib_xua/src/core/clocking/clockgen.xc
> +        printstr("clockValid=");printintln(valid);
Accidental debug print left in?

2024-01-15 18:44 UTC, xross approved these changes

2024-01-16 10:07 UTC, merged